name: ClassicPhysics
main: me.eddiep.ClassicPhysics
version: 0.3
load: POSTWORLD
authors: [hypereddie, pupnewfster]
website: eddiep.me
depend: [FastAsyncWorldEdit]
commands:
  pcl:
    description: Place only classic lava blocks
    usage: /<command>
    permission: classicphysics.pcl
    permission-message: You don't have <permission>
  pcw:
    description: Place only classic water blocks
    usage: /<command>
    permission: classicphysics.pcl
    permission-message: You don't have <permission>