name: ClassicPhysics
main: me.eddiep.ClassicPhysics
version: 0.2
load: POSTWORLD
author: hypereddie
website: eddiep.me
commands:
  setphysics:
    description: Change the physics settings of this world
    usage: /<command> <speed/level> <value> [world]
    permission: classicphysics.settings
    permission-message: You don't have <permission>