name: Lavasurvival
main: me.eddiep.minecraft.ls.Lavasurvival
version: 0.2
load: POSTWORLD
authors: [hypereddie, pupnewfster]
website: eddiep.me
softdepend: [ClassicPhysics, Necessities]
depend: [Vault]
commands:
  setupmap:
    description: Setup and add a new lavasurvival map!
    usage: /<command>
    permission: lavasurvival.setup
    permission-message: You don't have <permission>
    aliases: [setup]
  lvote:
    description: Vote for a map!
    usage: /<command> <number>
    permission: lavasurvival.lvote
    permission-message: You don't have <permission>
    aliases: [vote, v]
  endgame:
    description: Ends the current game.
    usage: /<command>
    permission: lavasurvival.endGame
    permission-message: You don't have <permission>
    aliases: [end]
  rules:
    description: Gives you a copy of the rules.
    usage: /<command>
    permission: lavasurvival.rules
    permission-message: You don't have <permission>
permissions:
    lavasurvival.*:
        description: Lavasurvival's permission nodes
        children:
            lavasurvival.setup: true
            lavasurvival.lvote: true
            lavasurvival.voteSpeak: true
            lavasurvival.endGame: true
            lavasurviva.donator: true
            lavasurvival.rules: true
    lavasurvival.lvote:
        description: Allows you to vote for maps.
        default: true
    lavasurvival.rules:
        description: Allows you to read the rules.
        default: true
    lavasurvival.setup:
        description: Allows you to setup and add a new lava survival map.
        default: op
    lavasurvival.voteSpeak:
        description: Allows you to speak during votes.
        default: op
    lavasurvival.endGame:
        description: Allows you to end the current game.
        default: op
    lavasurvival.donator:
        description: Allows you to buy donator blocks.
        default: op