name: Lavasurvival
main: me.eddiep.minecraft.ls.Lavasurvival
version: 0.4
load: POSTWORLD
authors: [hypereddie, pupnewfster]
website: eddiep.me
depend: [ClassicPhysics, Necessities]
commands:
  setupmap:
    description: Setup and add a new lavasurvival map!
    usage: /<command>
    permission: lavasurvival.setup
    aliases: [setup]
  lvote:
    description: Vote for a map!
    usage: /<command> <number>
    permission: lavasurvival.lvote
    aliases: [vote, v]
  endgame:
    description: Ends the current game, and sets it to <map> with the specified <gamemode>.
    usage: /<command> <map> <gamemode>
    permission: lavasurvival.endGame
    aliases: [end]
  rules:
    description: Gives you a copy of the rules.
    usage: /<command>
    permission: lavasurvival.rules
  airc:
    description: Check number of air blocks around you (20 radius)
    usage: /<command>
    permission: lavasurvival.airc
  spawn:
    description: Go back to map spawn
    usage: /<command>
    permission: lavasurvival.spawn
    aliases: [setup]
  calculatecpmap:
    description: Calculate the melt times of the blocks for Classic Physics.
    usage: /<command>
    permission: lavasurvival.calculateCPMap
    aliases: [ccpmap, ccpm]
permissions:
    lavasurvival.*:
        description: Lavasurvival's permission nodes
        children:
            lavasurvival.calculateCPMap: true
            lavasurvival.setup: true
            lavasurvival.lvote: true
            lavasurvival.voteSpeak: true
            lavasurvival.endGame: true
            lavasurviva.donator: true
            lavasurvival.seemmr: true
            lavasurvival.rules: true
            lavasurvival.spawn: true
    lavasurvival.lvote:
        description: Allows you to vote for maps.
        default: true
    lavasurvival.spawn:
        description: Allows you to go to spawn.
        default: true
    lavasurvival.rules:
        description: Allows you to read the rules.
        default: true
    lavasurvival.setup:
        description: Allows you to setup and add a new lava survival map.
        default: op
    lavasurvival.voteSpeak:
        description: Allows you to speak during votes.
        default: op
    lavasurvival.endGame:
        description: Allows you to end the current game.
        default: op
    lavasurvival.donator:
        description: Allows you to buy donator blocks.
        default: op
    lavasurvival.seemmr:
        description: Allows you to see your mmr
        default: op
    lavasurvival.calculateCPMap:
        description: Allows you to calculate a map for classic physics.
        default: op